### ISSUE TITLE
Can't set custom path to CodeSniffer binary review

### ISSUE THREAD

**Issue by liquorvicar** [sjparkinson/static-review#62]
This is hard-coded to 'vendor/bin/phpcs'. Should this be configurable?

**Comment by maschmann** [comment]
It definitely should! I've stumbeled upon that within an symfony project where binaries are linked to <project_path>/bin/ instead of vendor/bin/
This leads to a not so useful error in codesniffer, since there is no check if the phpcs executable exists. Also there's no requirement for codesniffer within static-review.
